In [122]:
import numpy as np

In [123]:
c=np.array([1,7,3,4,5])
print(c+5)

[ 6 12  8  9 10]


In [4]:
set([i for sublist in a for i in sublist])

TypeError: 'int' object is not iterable

In [17]:
import collections


def flatten(x):
    if isinstance(x, collections.Iterable):
        return [a for i in x for a in flatten(i)]
    else:
        return [x]


a = [1, 2, 3, [1, [2, 4]]]
out = set(flatten(a))
out

{1, 2, 3, 4}

In [16]:
def flatten(S):
    if S == []:
        return S
    if isinstance(S[0], list):
        return flatten(S[0]) + flatten(S[1:])
    return S[:1] + flatten(S[1:])

a = [1, 2, 3, [1, [2, 4]]]
out = set(flatten(a))
out

{1, 2, 3, 4}

In [30]:
f = lambda x: [i for i in x]
g = lambda x: f(x) if isinstance(x, list) else x

In [31]:
g(a)

[1, 2, 3, [1, [2, 4]]]

In [18]:
set([num for item in a for num in (item if isinstance(item, list) else (item,))])

TypeError: unhashable type: 'list'

In [34]:
from functools import reduce

In [36]:
newlist = reduce(lambda x,y: x+y, a)

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [44]:
a

[1, 2, 3, [1, [2, 4]]]

In [ ]:
lambda *n: (e for a in n for e in (flatten(*a) if isinstance(a, (tuple, list)) else (a,)))

In [56]:
f = lambda *n: (e for a in n for e in (f(*a) if isinstance(a, (tuple, list)) else (a,)))

set(f(a))

In [98]:
n = [4, [3,4]]

In [101]:
f = lambda *n: [i for a in n for i in (f(*a) if isinstance(a, (tuple, list)) else (a,))]

In [102]:
f(n)

[4, 3, 4]

In [114]:
a = [5,[3,7]]

In [115]:
(a if isinstance(a, (tuple, list)) else (a,))

[5, [3, 7]]

In [119]:
a = 5

In [120]:
(a if isinstance(a,list) else (a,))

(5,)

In [124]:
import torch
a=torch.randn(3,100)
b=torch.randn(3,100)
row_num = a.size()[0] # 3

# Given two matrix with shape (n1,n2)
# I want to have the row-wise `matmul` results which will result in a tensor with size (n1, ) 

scores = []
for i in range(row_num):
    score_i = a[i,:].matmul(b[i,:])
    scores.append(score_i)
expected_result = torch.tensor(scores)

In [125]:
expected_result

tensor([ 4.8495,  3.3092, -2.7939])

In [130]:
torch.einsum('ij,ij->i',a,b)

tensor([ 4.8495,  3.3092, -2.7939])

In [167]:
torch.diagonal(torch.tensordot(a,b,dims=([1],[1])))

tensor([ 4.8495,  3.3092, -2.7939])

In [168]:
torch.dot(a, b.T)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [171]:
np.diagonal(torch.matmul(a, b.T))

array([ 4.8495054,  3.309207 , -2.7938733], dtype=float32)

In [174]:
np.diagonal(a @ b.T)

array([ 4.8495054,  3.309207 , -2.7938733], dtype=float32)

In [151]:
a.shape

torch.Size([3, 100])

In [152]:
b.shape

torch.Size([3, 100])

tensor([[  4.8495, -13.4082,  -7.3157],
        [ -8.7273,   3.3092,   0.8553],
        [ -6.9103,  14.5447,  -2.7939]])

In [177]:
import pandas as pd

In [182]:
df = pd.read_clipboard()

In [183]:
df

,inventory_partner,inventory_partner2,calc
0,A1,aa,1
1,A2,bb,2
2,A3,cc,5
3,A4,dd,4
4,A5,ee,5
5,A6,ff,3


In [184]:
df.groupby('inventory_partner')

In [53]:
import pandas as pd

bbgDf = pd.DataFrame({'BBG': ['700', 'UNI', 'CSL', 'CSL', 'UNI'],
                        'ID': ['AA','BB','CC','DD','EE'],
                     'TICKER': ['1.hk','2.hk','3.hk','4.hk','5.hk'],
                     'AMOUNT': [100.01,200.45,300.12,400.98,500.45]})

f = lambda x : x.sum() if x.dtype=='float' else ', '.join(x)
g = {'ID':f,'TICKER':f,'AMOUNT':f}

bbgDf = bbgDf.groupby('BBG').agg(g).reset_index()
print(bbgDf)

   BBG      ID      TICKER  AMOUNT
0  700      AA        1.hk  100.01
1  CSL  CC, DD  3.hk, 4.hk  701.10
2  UNI  BB, EE  2.hk, 5.hk  700.90
