In [1]:
import pandas as pd
import numpy as np
import itertools
from collections import defaultdict
from tensorflow.keras import layers, Model, utils

In [3]:
d = {'all': 
     ['463\tQuels problèmes ce concept résout-il ? Nous revenons à la fiche de fonction, elle résout ce problème de technologie, avec une grande facilité.\tM',
      '2647\tCela signifie donc que pour le résoudre, nous devons mettre à jour tous les Magelis que nous avons............\tC',
      "5391\tJe ne pense pas que cela changera la qualité du produit, donc cela ne changera rien pour moi. Je continuerai à l'acheter.\tM",
      "1120\tSur les stations de pompage, c'est très intéressant car environnement pollué, corrosif ?\tM"],
     "am": ['4021\tC\'est bien pensé. La représentation colorée et photographique est belle et attrayante. L\'évocation photographique dans la démo est intéressante. La double entrée : le manuel et l\'ordinateur, 
 'est vraiment intéressant. Je ne l\'ai pas encore expérimenté.\tM',"160\tJe suis intéressé par le suivi des performances dans le temps, mais je dispose d'indicateurs simples, comme la consommation d'une chaufferie."]}

SyntaxError: EOL while scanning string literal (<ipython-input-3-4cee7b7dd72b>, line 5)

In [15]:
d = {'all': ['463\tQuels problèmes ce concept résout-il ? Nous revenons à la fiche de fonction, elle résout ce problème de technologie, avec une grande facilité.\tM',
         '2647\tCela signifie donc que pour le résoudre, nous devons mettre à jour tous les Magelis que nous avons............\tC',
         "5391\tJe ne pense pas que cela changera la qualité du produit, donc cela ne changera rien pour moi. Je continuerai à l'acheter.\tM",
         "1120\tSur les stations de pompage, c'est très intéressant car environnement pollué, corrosif ?\tM"],
 "am": ['4021\tC\'est bien pensé. La représentation colorée et photographique est belle et attrayante. L\'évocation photographique dans la démo est intéressante. La double entrée : le manuel et l\'ordinateur, c\'est vraiment intéressant. Je ne l\'ai pas encore expérimenté.\tM',
        "160\tJe suis intéressé par le suivi des performances dans le temps, mais je dispose d'indicateurs simples, comme la consommation d'une chaufferie."]}

In [16]:
for k, v in d.items():
    v.pop(0)
    v = [i.split("\t") for i in v]
    df = pd.DataFrame(v, columns = ['identifiant', 'verbatim', 'etiquette'] )
    df['id_langue'] = k
    print(df.head())

  identifiant                                           verbatim etiquette  \
0        2647  Cela signifie donc que pour le résoudre, nous ...         C   
1        5391  Je ne pense pas que cela changera la qualité d...         M   
2        1120  Sur les stations de pompage, c'est très intére...         M   

  id_langue  
0       all  
1       all  
2       all  


ValueError: 3 columns passed, passed data had 2 columns

In [7]:
 identifiant                                           verbatim etiquette  \
0         463  Quels problèmes ce concept résout-il ? Nous re...         M   
1        2647  Cela signifie donc que pour la solution, vous ...         C   
2        5391  Cela ne changera pas la qualité du produit, je...         M   
3        1120  C'est très intéressant, parce que c'est un env...         M   
4        4021  C'est bien pensé. La couleur, la présentation ...         M   

  id_langue  
0       aBr  
1       aBr  
2       aBr  
3       aBr  
4       aBr  

0         463  Quels problèmes ce concept résout-il ? Nous re...         M   
1        2647  Cela signifie donc que pour le résoudre, nous ...         C   
2        5391  Je ne pense pas que cela changera la qualité d...         M   
3        1120  Sur les stations de pompage, c'est très intére...         M   
4        4021  C'est bien pensé. La représentation colorée et...         M   
 
0       all  
1       all  
2       all  
3       all  
4       all

0         463  Quels problèmes ce concept résout-il ? Nous re...         M   
1        2647  Cela signifie donc que pour le résoudre, nous ...         C   
2        5391  Je ne pense pas que cela changera la qualité d...         M   
3        1120  Sur les stations de pompage, c'est très intére...         M   
4        4021  C'est bien pensé. La représentation colorée et...         M   
 
0       german  
1       german  
2       german 
3       german 
4       german

ParserError: Expected 11 fields in line 8, saw 12. Error could possibly be due to quotes being ignored when a multi-char delimiter is used.

In [19]:
df = pd.DataFrame(['(F) Red Apples', '(F) Oranges', 'Purple (F)Grapes', '(F) Fried Apples'])
df.columns = ['Column A']

In [20]:
df

Column A
0    (F) Red Apples
1       (F) Oranges
2  Purple (F)Grapes
3  (F) Fried Apples

In [24]:
df['Column A'].str.replace('(F)','', regex=False)

0       Red Apples
1          Oranges
2    Purple Grapes
3     Fried Apples
Name: Column A, dtype: object

In [ ]:
**Column A**

 (F) Red Apples

 (F) Oranges 

 Purple (F)Grapes

 (F) Fried Apples

In [28]:
from sklearn.model_selection import train_test_split

df = pd.DataFrame(np.random.random((100,10)))

train, test = train_test_split(df, test_size=0.2)
train.shape, test.shape

((80, 10), (20, 10))

In [32]:
test = df.sample(frac=0.2)
train = df.loc[~df.index.isin(test.index)]

In [ ]:
df.loc[~df.index.isin(t)]

(80, 10)

In [70]:
test_idx = np.random.choice(range(100), 20, replace=False) #approx 20% random indexes 

test = df.loc[df.index.isin(test_idx)]
train = df.loc[~df.index.isin(test_idx)]
train.shape, test.shape

((80, 10), (20, 10))

In [53]:
train.index

Int64Index([ 0,  1,  2,  3,  5,  6,  9, 11, 14, 15, 17, 18, 19, 20, 21, 22, 23,
            24, 25, 26, 27, 28, 30, 31, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
            43, 44, 46, 47, 48, 49, 51, 52, 53, 55, 56, 57, 58, 59, 60, 62, 63,
            64, 65, 66, 67, 68, 69, 70, 71, 72, 74, 76, 77, 78, 79, 80, 81, 83,
            84, 85, 86, 87, 88, 89, 90, 91, 92, 95, 96, 97, 99],
           dtype='int64')

In [61]:
sorted(test.index)

[4, 7, 8, 10, 12, 13, 16, 29, 32, 45, 50, 54, 61, 73, 75, 82, 93, 94, 98]

In [60]:
sorted(test_idx)

[4, 7, 8, 10, 12, 13, 16, 29, 32, 45, 45, 50, 54, 61, 73, 75, 82, 93, 94, 98]

(80, 10)

In [74]:
df = pd.read_clipboard()
df

station  year  observations
0      3939  2000      0.346518
1      3939  2001      0.278250
2      3939  2002      1.096147
3      3939  2003      0.423948
4      3939  2004      0.000000
5      3939  2005      0.000000
6      3939  2006      0.000000
7      3939  2007      0.663922
8      3939  2008      0.000000
9      3939  2009      0.000000
10     3939  2010      0.000000
11     3939  2011      2.921322
12     3939  2012      1.463399
13     3939  2013      1.402697
14     3939  2014      0.000000
15     3939  2015      0.000000
16     3939  2016      0.000000
17     3939  2017      0.000000
18     3939  2018      0.000000
19     3939  2019      2.599236
20     3939  2020      1.428136
21     3953  2000      5.893202
22     3953  2001      7.227092
23     3953  2002      6.489147
24     3953  2003      4.961213
25     3953  2004      0.000000
26     3953  2005      0.000000
27     3953  2006      5.273121
28     3953  2007      0.000000
29     3953  2008      0.000000
30     3953  2009      0.000000
31     3953  2010      5.591221
32     3953  2011      0.000000
33     3953  2012      0.000000
34     3953  2013      4.797106
35     3953  2014      8.109661
36     3953  2015      0.000000
37     3953  2016      1.798583
38     3953  2017      0.000000
39     3953  2018      0.000000
40     3953  2019      0.000000
41     3953  2020      6.440142
42     3977  2000     14.236954
43     3977  2001     17.216910
44     3977  2002     10.210559
45     3977  2003      0.000000
46     3977  2004      0.000000
47     3977  2005     10.463710
48     3977  2006      0.000000
49     3977  2007      0.000000

In [ ]:
pd.Series.interpolate()

In [81]:
interp = lambda g: g.replace(0, np.nan).interpolate(method='linear')
df.groupby('station')['observations'].apply(interp)

0      0.346518
1      0.278250
2      1.096147
3      0.423948
4      0.483942
5      0.543935
6      0.603928
7      0.663922
8      1.228272
9      1.792622
10     2.356972
11     2.921322
12     1.463399
13     1.402697
14     1.602120
15     1.801543
16     2.000967
17     2.200390
18     2.399813
19     2.599236
20     1.428136
21     5.893202
22     7.227092
23     6.489147
24     4.961213
25     5.065182
26     5.169152
27     5.273121
28     5.352646
29     5.432171
30     5.511696
31     5.591221
32     5.326516
33     5.061811
34     4.797106
35     8.109661
36     4.954122
37     1.798583
38     2.958973
39     4.119363
40     5.279752
41     6.440142
42    14.236954
43    17.216910
44    10.210559
45    10.294943
46    10.379326
47    10.463710
48    10.463710
49    10.463710
Name: observations, dtype: float64

In [83]:
import numpy as np 

a = np.array([[12,45,50,-600,30,23.2,232,-44,12],
             [45,50,60,30,23.2,232,-44,12,23],
             [50,60,30,23.2,232,-44,12,34,12],
             [60,30,23.2,232,-44,12,120,3,4],
             [-300,23.2,232,-44,12,23,23,2,12],
             [23.2,-232,-44,12,34,1,2,300.3,5]], dtype='object')

b= np.array([-12.4,-13.4,-44,-100,-6.3,-11,-10,-1.1,-0.3])

#------

exp = [[12,45,50,0,0,0,0,0,0],
[45,50,60,0,0,0,0,0,0],
[50,60,30,0,0,0,0,0,0],
[60,30,23.2,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0],
[23.2,0,0,0,0,0,0,0,0]]

In [85]:
print(a)

[[12 45 50 -600 30 23.2 232 -44 12]
 [45 50 60 30 23.2 232 -44 12 23]
 [50 60 30 23.2 232 -44 12 34 12]
 [60 30 23.2 232 -44 12 120 3 4]
 [-300 23.2 232 -44 12 23 23 2 12]
 [23.2 -232 -44 12 34 1 2 300.3 5]]


In [110]:
(a<-100).astype(int)

array([[0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0]])

In [119]:
a[]

array([-600, 45, 50, 60, -300, -232], dtype=object)

In [129]:
np.where(np.cumsum(a<-100,1), 0, a)

array([[12, 45, 50, 0, 0, 0, 0, 0, 0],
       [45, 50, 60, 30, 23.2, 232, -44, 12, 23],
       [50, 60, 30, 23.2, 232, -44, 12, 34, 12],
       [60, 30, 23.2, 232, -44, 12, 120, 3, 4],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [23.2, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=object)

array([[12, 45, 50, 0, 0, 0, 0, 0, 0],
       [45, 50, 60, 30, 23.2, 232, -44, 12, 23],
       [50, 60, 30, 23.2, 232, -44, 12, 34, 12],
       [60, 30, 23.2, 232, -44, 12, 120, 3, 4],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [23.2, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=object)

In [138]:
b = np.array([-12.4,-13.4,-44,-100,-6.3,-11,-10,-1.1,-0.3])

np.where(np.cumsum(b<=-100), 0, b)

array([-12.4, -13.4, -44. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ])

array([-12.4, -13.4, -44. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ])

In [136]:
(a==-100)

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False]])

In [140]:
c = np.array([45,50,60,30,23.2,232,-44,12,23])

np.where(np.cumsum(c<=30), 0, c)

array([45., 50., 60.,  0.,  0.,  0.,  0.,  0.,  0.])

array([45., 50., 60.,  0.,  0.,  0.,  0.,  0.,  0.])

In [146]:
np.where(np.cumsum(a<=-100, axis=1) + np.cumsum(b<=-100), 0, a)

array([[12, 45, 50, 0, 0, 0, 0, 0, 0],
       [45, 50, 60, 0, 0, 0, 0, 0, 0],
       [50, 60, 30, 0, 0, 0, 0, 0, 0],
       [60, 30, 23.2, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [23.2, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=object)

array([0, 0, 0, 1, 1, 1, 1, 1, 1])

In [ ]:
[45,50,60,0,0,0,0,0,0]

In [120]:
np.argmax(a<-100,1)

array([3, 0, 0, 0, 0, 1])

In [152]:
a = np.array([[12,45,50,-600,30,23.2,232,-44,12],
             [45,50,60,30,23.2,232,-44,12],
             [50,60,30,23.2,232,-44,12,34,12],
             [60,30,23.2,232,-44,12,120,3],
             [-300,23.2,232,-44,12,23,23,2,12],
             [23.2,-232,-44,12,34,1,2,300.3,5]], dtype='object')

[[12, 45, 50, -600, 30, 23.2, 232, -44, 12],
 [45, 50, 60, 30, 23.2, 232, -44, 12],
 [50, 60, 30, 23.2, 232, -44, 12, 34, 12],
 [60, 30, 23.2, 232, -44, 12, 120, 3],
 [-300, 23.2, 232, -44, 12, 23, 23, 2, 12],
 [23.2, -232, -44, 12, 34, 1, 2, 300.3, 5]]

In [159]:
[np.cumsum(i for i in a.tolist()]

[[12, 45, 50, -600, 30, 23.2, 232, -44, 12],
 [45, 50, 60, 30, 23.2, 232, -44, 12],
 [50, 60, 30, 23.2, 232, -44, 12, 34, 12],
 [60, 30, 23.2, 232, -44, 12, 120, 3],
 [-300, 23.2, 232, -44, 12, 23, 23, 2, 12],
 [23.2, -232, -44, 12, 34, 1, 2, 300.3, 5]]

3

In [184]:
idx = np.argwhere(b<=-100)[0][0]

for i in a.tolist():
    for j,k in enumerate(i):
        if k<=-100:
            print(j)
    print(idx)

3
3
3
3
3
0
3
1
3


In [193]:
[[0 if j<=-100 else sublist[i] for i,j in enumerate(sublist)] for sublist in a.tolist()]

[[12, 45, 50, 0, 30, 23.2, 232, -44, 12],
 [45, 50, 60, 30, 23.2, 232, -44, 12],
 [50, 60, 30, 23.2, 232, -44, 12, 34, 12],
 [60, 30, 23.2, 232, -44, 12, 120, 3],
 [0, 23.2, 232, -44, 12, 23, 23, 2, 12],
 [23.2, 0, -44, 12, 34, 1, 2, 300.3, 5]]

array([list([12, 45, 50, -600, 30, 23.2, 232, -44, 12]),
       list([45, 50, 60, 30, 23.2, 232, -44, 12]),
       list([50, 60, 30, 23.2, 232, -44, 12, 34, 12]),
       list([60, 30, 23.2, 232, -44, 12, 120, 3]),
       list([-300, 23.2, 232, -44, 12, 23, 23, 2, 12]),
       list([23.2, -232, -44, 12, 34, 1, 2, 300.3, 5])], dtype=object)

1 2 3 4


In [161]:
[np.cumsum((np.array(i)<=-100)+(b<=-100)) for i in a.tolist()]

ValueError: operands could not be broadcast together with shapes (8,) (9,) 

In [162]:
(b<=-100)

array([False, False, False,  True, False, False, False, False, False])

In [ ]:
a[(m!=0).argmax(0), np.arange(m.shape[1])]