In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = [['Food industry', '936', '845', '901', '924', '943', '947', '990', '956', '928', '813', '699', '762', '843', '768', '608', '641', '562', '493', '490', '488', '484', '495', '460', '440', '390', '402', '339', '325'], ['Mineral industry', '3065', '2659', '2781', '2797', '3206', '3152', '2998', '3252', '3139', '3543', '3624', '3451', '3189', '3358', '3543', '3724', '3533', '3453', '2961', '3312', '3378', '3393', '3095', '3159', '3224', '3235', '3205', '3229'], ['Iron- and metal industry', '5584', '5434', '5821', '6065', '6511', '6652', '6528', '6612', '6611', '6639', '7255', '7375', '7483', '7605', '7303', '7148', '7433', '7061', '4290', '6762', '6303', '5583', '5715', '5648', '5774', '5869', '6253', '5693']] 

In [ ]:
print(data)

In [ ]:
arr = [['0.55070000', '879.00000000'], ['0.55350000', '879.00000000'], ['0.55640000', '879.00000000'], ['0.56210000', '879.00000000'], ['0.56490000', '879.00000000'], ['0.56780000', '879.00000000'], ['0.57060000', '879.00000000'], ['0.54500000', '899.00000000'], ['0.56370000', '901.00000000'], ['0.53070000', '908.00000000'], ['0.57350000', '916.00000000'], ['0.55000000', '9172.00000000'], ['0.56300000', '939.00000000'], ['0.54490000', '94.00000000'], ['0.56040000', '96.00000000'], ['0.54960000', '999.00000000']]

In [ ]:
arr2 = [[float(j) for j in i] for i in arr]
sorted(arr2, key=lambda x: x[1])

In [ ]:
sorted(arr, key=lambda x: float(x[1]))

In [ ]:
import numpy as np

A = np.random.random((10000, 100))
B = np.random.random((100, 1000))
C = np.random.random((1000, 5))
D = np.random.random((5, 333))

list_of_arrays = [A, B, C, D]

# the actual dot multiplication
output = np.linalg.multi_dot(list_of_arrays)

In [ ]:
df = pd.DataFrame(np.random.randint(0,100,size=(10,10)))
df

In [ ]:

n

In [ ]:
from itertools import product
from random import sample

p = 0.1
n = int(df.shape[0]*df.shape[1]*p)          #Calculate count of nans

#Sample exactly n indexes
ids = sample(list(product(range(df.shape[0]), range(df.shape[1]))), n)
idx, idy = list(zip(*ids))

data = df.to_numpy().astype(float)            #Get data as numpy
data[idx, idy]=np.nan                         #Update numpy view with np.nan

#Assign to new dataframe
new_df = pd.DataFrame(data, columns=df.columns, index=df.index)
print(new_df)

      0     1     2     3     4     5     6     7     8     9
0  52.0  50.0  24.0  81.0  10.0   NaN   NaN  75.0  14.0  81.0
1  45.0   3.0  61.0  67.0  93.0   NaN  90.0  34.0  39.0   4.0
2   1.0   NaN   NaN  71.0  57.0  88.0   8.0   9.0  62.0  20.0
3  78.0   3.0  82.0   1.0  75.0  50.0  33.0  66.0  52.0   8.0
4  11.0  46.0  58.0  23.0   NaN  64.0  47.0  27.0   NaN  21.0
5  70.0  35.0  54.0   NaN  70.0  82.0  69.0  94.0  20.0   NaN
6  54.0  84.0  16.0  76.0  77.0  50.0  82.0  31.0   NaN  31.0
7  71.0  79.0  93.0  11.0  46.0  27.0  19.0  84.0  67.0  30.0
8  91.0  85.0  63.0   1.0  91.0  79.0  80.0  14.0  75.0   1.0
9  50.0  34.0   8.0   8.0  10.0  56.0  49.0  45.0  39.0  13.0

In [ ]:
np.random.random_sample()

In [ ]:
np.random.randint(0, df.shape[0], (n,))

In [ ]:
list(zip(idx, idy))

In [ ]:
df.ix[list(zip(idx,idy))]

In [ ]:
d = {'192.168.0.28': {'hostnames': [{'name': '', 'type': ''}], 'addresses': {'ipv4': '192.168.0.28'}, 'vendor': {}, 'status': {'state': 'up', 'reason': 'conn-refused'}, 'tcp': {22: {'state': 'open', 'reason': 'syn-ack', 'name': 'ssh', 'product': 'OpenSSH', 'version': '7.9p1 Raspbian 10+deb10u2', 'extrainfo': 'protocol 2.0', 'conf': '10', 'cpe': 'cpe:/o:linux:linux_kernel'}}}}
d

In [ ]:
import pandas as pd

In [ ]:
pd.json_normalize(d)

In [ ]:
import numpy as np


a1 = [1,2,3,4]
a2 = [11,22,33,44]
a3 = [111,222,333,444]
a4 = [1111,2222,3333,4444]

a = []
for x in a1:
    for y in a2:
        for k in a3:
            for l in a4:
                a.append((x, y, k, l))


na = np.array(a)

In [ ]:
na

In [ ]:
df

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import KNNImputer

d = { 'year': [2019,2020,2019,2020,np.nan,np.nan], 'cat1': [1,2,3,4,np.nan,np.nan], 'cat2': ['c1','c1','c1','c2',np.nan,np.nan]}
df = pd.DataFrame(data=d)
df

In [ ]:

knn = KNNImputer(n_neighbors=5)

lb.fit(df['cat2'].dropna())
mapping = {v:k for k,v in enumerate(lb.classes_)}
df['cat2'] = df['cat2'].replace(mapping)

In [ ]:
df

In [ ]:
knn.fit_transform(df)

In [ ]:
A	B	C	D	E
2019	1	6	C	A
2020	2	5	D	B
2019	3	4	E	C
2020	4	3	F	A
2019	5	2	G	B
2020	6	1	H	C

In [ ]:
df = pd.read_clipboard()
df

In [ ]:
df.to_dict('list')

In [ ]:
data = {'A': [2019, 2020, 2019, 2020, 2019, 2020],
        'B': [1, 2, 3, 4, 5, 6],
        'C': [6, 5, 4, 3, 2, 1],
        'D': ['C', 'D', 'E', 'F', 'G', 'H'],
        'E': ['A', 'B', 'C', 'A', 'B', 'C'],
        'F': [1,2,3,3,4,2]
       }

df = pd.DataFrame(data)
empty = pd.DataFrame(columns=df.columns, index=df.index)[:4]
df_new = df.append(empty).reset_index(drop=True)
print(df_new)

      A    B    C    D    E    F
0  2019    1    6    C    A    1
1  2020    2    5    D    B    2
2  2019    3    4    E    C    3
3  2020    4    3    F    A    3
4  2019    5    2    G    B    4
5  2020    6    1    H    C    2
6   NaN  NaN  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN
9   NaN  NaN  NaN  NaN  NaN  NaN

In [ ]:
import numpy as np
import scipy as sp
import pandas as pd


#Curve fitting (linear)
def f(x, m, c):
    return m*x+c     #Modify to extrapolate for exponential sequences etc.

#Interpolate continous linear
def continous_interpolate(s):
    clean = s.dropna()
    popt, pcov = sp.optimize.curve_fit(f, clean.index, clean)
    output = [round(i) for i in f(s.index, *popt)]  #Remove the round() for float values
    return pd.Series(output)

#Smallest Repeating sub-sequence
def pattern(inputv):
    '''
    https://stackoverflow.com/questions/6021274/finding-shortest-repeating-cycle-in-word
    '''
    pattern_end =0
    for j in range(pattern_end+1,len(inputv)):

        pattern_dex = j%(pattern_end+1)
        if(inputv[pattern_dex] != inputv[j]):

            pattern_end = j;
            continue

        if(j == len(inputv)-1):
            return inputv[0:pattern_end+1];
    return inputv;

#Categorical repeat imputation
def categorical_repeat(s):
    clean = s.dropna()
    cycle = pattern(clean)
    
    repetitions = (len(s)//len(cycle))+1
    output = np.tile(cycle, repetitions)[:len(s)]
    return pd.Series(output)

#continous sequence of alphabets
def alphabet(s):
    alp = 'abcdefghijklmnopqrstuvwxyz'
    alp2 = alp*((len(s)//len(alp))+1)
    
    start = s[0]
    idx = alp2.find(start.lower())
    output = alp2[idx:idx+len(s)]

    if start.isupper():
        output = output.upper()
    
    return pd.Series(list(output))

#If no pattern then just ffill
def other(s):
    return s.ffill()

In [ ]:
config = {'A':categorical_repeat,
          'B':continous_interpolate, 
          'C':continous_interpolate, 
          'D':alphabet,
          'E':categorical_repeat, 
          'F':other}

output_df = df_new.agg(config)
print(output_df)

      A   B  C  D  E  F
0  2019   1  6  C  A  1
1  2020   2  5  D  B  2
2  2019   3  4  E  C  3
3  2020   4  3  F  A  3
4  2019   5  2  G  B  4
5  2020   6  1  H  C  2
6  2019   7  0  I  A  2
7  2020   8 -1  J  B  2
8  2019   9 -2  K  C  2
9  2020  10 -3  L  A  2

In [ ]:
import pandas as pd
d = { 'year': [2019,2020,2019,2020,np.nan,np.nan], 'cat1': [1,2,3,4,np.nan,np.nan], 'cat2': ['c1','c1','c1','c2',np.nan,np.nan]}
df = pd.DataFrame(data=d)
df

In [ ]:
config = {'year':categorical_repeat, 
          'cat1':continous_interpolate, 
          'cat2':other}

print(df.agg(config))

     year  cat1 cat2
0  2019.0     1   c1
1  2020.0     2   c1
2  2019.0     3   c1
3  2020.0     4   c2
4  2019.0     5   c2
5  2020.0     6   c2

In [ ]:
categorical_repeat(df_new['A'])

In [ ]:
pattern([2019, 2020, 2019, 2020, 2019, 2020])

In [ ]:
df_new['A'].dropna()

In [8]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [12]:
model = Sequential([
    Dense(1, input_shape=(1,))
])

model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 1)                 2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [ ]:

model.compile(optimizer='sgd',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# train
hist = model.fit(t1_train, goal_train,
          batch_size=32, epochs=25,
          validation_data=(t1_val, goal_val))

In [13]:
mat1, mat2, mat3, mat4 = np.random.rand(3, 3), np.random.rand(3, 3), np.random.rand(3, 3), np.random.rand(3, 3)

In [18]:
[i.shape for i in [mat1, mat2, mat3, mat4]]

[(3, 3), (3, 3), (3, 3), (3, 3)]

In [15]:
res = np.empty((8, 7, 6, 5))

for i in range(8):
    for j in range(7):
        for p in range(6):
            for q in range(5):
                res[i, j, p, q] = np.linalg.norm(i * mat1 + j * mat2 + p * mat3 + q * mat4)

In [17]:
res.shape

(8, 7, 6, 5)

In [19]:
np.linalg.norm(i * mat1 + j * mat2 + p * mat3 + q * mat4)

35.71236801413382

(4, 3, 3)

In [24]:
for i in range(8):
    for j in range(7):
        for p in range(6):
            for q in range(5):
                i * mat1 + j * mat2 + p * mat3 + q * mat4

0 0 0 0
0 0 0 1
0 0 0 2
0 0 0 3
0 0 0 4
0 0 1 0
0 0 1 1
0 0 1 2
0 0 1 3
0 0 1 4
0 0 2 0
0 0 2 1
0 0 2 2
0 0 2 3
0 0 2 4
0 0 3 0
0 0 3 1
0 0 3 2
0 0 3 3
0 0 3 4
0 0 4 0
0 0 4 1
0 0 4 2
0 0 4 3
0 0 4 4
0 0 5 0
0 0 5 1
0 0 5 2
0 0 5 3
0 0 5 4
0 1 0 0
0 1 0 1
0 1 0 2
0 1 0 3
0 1 0 4
0 1 1 0
0 1 1 1
0 1 1 2
0 1 1 3
0 1 1 4
0 1 2 0
0 1 2 1
0 1 2 2
0 1 2 3
0 1 2 4
0 1 3 0
0 1 3 1
0 1 3 2
0 1 3 3
0 1 3 4
0 1 4 0
0 1 4 1
0 1 4 2
0 1 4 3
0 1 4 4
0 1 5 0
0 1 5 1
0 1 5 2
0 1 5 3
0 1 5 4
0 2 0 0
0 2 0 1
0 2 0 2
0 2 0 3
0 2 0 4
0 2 1 0
0 2 1 1
0 2 1 2
0 2 1 3
0 2 1 4
0 2 2 0
0 2 2 1
0 2 2 2
0 2 2 3
0 2 2 4
0 2 3 0
0 2 3 1
0 2 3 2
0 2 3 3
0 2 3 4
0 2 4 0
0 2 4 1
0 2 4 2
0 2 4 3
0 2 4 4
0 2 5 0
0 2 5 1
0 2 5 2
0 2 5 3
0 2 5 4
0 3 0 0
0 3 0 1
0 3 0 2
0 3 0 3
0 3 0 4
0 3 1 0
0 3 1 1
0 3 1 2
0 3 1 3
0 3 1 4
0 3 2 0
0 3 2 1
0 3 2 2
0 3 2 3
0 3 2 4
0 3 3 0
0 3 3 1
0 3 3 2
0 3 3 3
0 3 3 4
0 3 4 0
0 3 4 1
0 3 4 2
0 3 4 3
0 3 4 4
0 3 5 0
0 3 5 1
0 3 5 2
0 3 5 3
0 3 5 4
0 4 0 0
0 4 0 1
0 4 0 2
0 4 0 3
0 4 0 4


5 4 5 1
5 4 5 2
5 4 5 3
5 4 5 4
5 5 0 0
5 5 0 1
5 5 0 2
5 5 0 3
5 5 0 4
5 5 1 0
5 5 1 1
5 5 1 2
5 5 1 3
5 5 1 4
5 5 2 0
5 5 2 1
5 5 2 2
5 5 2 3
5 5 2 4
5 5 3 0
5 5 3 1
5 5 3 2
5 5 3 3
5 5 3 4
5 5 4 0
5 5 4 1
5 5 4 2
5 5 4 3
5 5 4 4
5 5 5 0
5 5 5 1
5 5 5 2
5 5 5 3
5 5 5 4
5 6 0 0
5 6 0 1
5 6 0 2
5 6 0 3
5 6 0 4
5 6 1 0
5 6 1 1
5 6 1 2
5 6 1 3
5 6 1 4
5 6 2 0
5 6 2 1
5 6 2 2
5 6 2 3
5 6 2 4
5 6 3 0
5 6 3 1
5 6 3 2
5 6 3 3
5 6 3 4
5 6 4 0
5 6 4 1
5 6 4 2
5 6 4 3
5 6 4 4
5 6 5 0
5 6 5 1
5 6 5 2
5 6 5 3
5 6 5 4
6 0 0 0
6 0 0 1
6 0 0 2
6 0 0 3
6 0 0 4
6 0 1 0
6 0 1 1
6 0 1 2
6 0 1 3
6 0 1 4
6 0 2 0
6 0 2 1
6 0 2 2
6 0 2 3
6 0 2 4
6 0 3 0
6 0 3 1
6 0 3 2
6 0 3 3
6 0 3 4
6 0 4 0
6 0 4 1
6 0 4 2
6 0 4 3
6 0 4 4
6 0 5 0
6 0 5 1
6 0 5 2
6 0 5 3
6 0 5 4
6 1 0 0
6 1 0 1
6 1 0 2
6 1 0 3
6 1 0 4
6 1 1 0
6 1 1 1
6 1 1 2
6 1 1 3
6 1 1 4
6 1 2 0
6 1 2 1
6 1 2 2
6 1 2 3
6 1 2 4
6 1 3 0
6 1 3 1
6 1 3 2
6 1 3 3
6 1 3 4
6 1 4 0
6 1 4 1
6 1 4 2
6 1 4 3
6 1 4 4
6 1 5 0
6 1 5 1
6 1 5 2
6 1 5 3
6 1 5 4
6 2 0 0


In [64]:
res = np.empty((8, 7, 6, 5))

for i in range(8):
    for j in range(7):
        for p in range(6):
            for q in range(5):
                res[i, j, p, q] = np.linalg.norm(i * mat1 + j * mat2 + p * mat3 + q * mat4)

True

In [49]:
res.shape, np.stack([mat1, mat2, mat3, mat4]).shape

((1680, 4), (4, 3, 3))

In [84]:
from itertools import cycle

n = 8
values = cycle([0, 'x'])


[[next(values) for i in range(n)] for j in range(n)]

[[0, 'x', 0, 'x', 0, 'x', 0, 'x'],
 [0, 'x', 0, 'x', 0, 'x', 0, 'x'],
 [0, 'x', 0, 'x', 0, 'x', 0, 'x'],
 [0, 'x', 0, 'x', 0, 'x', 0, 'x'],
 [0, 'x', 0, 'x', 0, 'x', 0, 'x'],
 [0, 'x', 0, 'x', 0, 'x', 0, 'x'],
 [0, 'x', 0, 'x', 0, 'x', 0, 'x'],
 [0, 'x', 0, 'x', 0, 'x', 0, 'x']]

In [99]:
r = 'X '*9
board = [r]*9
board[::2]=[r[1:]+r

SyntaxError: unexpected EOF while parsing (<ipython-input-99-ec5c9d13b51b>, line 3)

In [113]:
n = 5
tile='X'
fill=' '

fill.join(tile*n), tile.join(fill*n)

'X X X X X'

' X X X X '

In [ ]:
list.pop(0)

In [ ]:
norm(3,)

In [ ]:
4X4, 5X5, 3

QXV, 1,2,3,4,5 X 1,2,3,4,5, 3

In [183]:
print(coords[:,:,None,:,None,:].shape)
print(coords[:,None,:,None,:,:].shape)
print(diff.shape)

(8, 4, 1, 5, 1, 3)
(8, 1, 4, 1, 5, 3)
(8, 4, 4, 5, 5, 3)


In [220]:
#Original list of 8 coordinate lists each with 20 (x,y,z) values
coords = [np.random.random((20,3)) for i in range(8)]

#Stack the coords to get a single tensor
coords = np.stack(coords) #(8,20,3)

#Chunk each tensor to break it into 4 parts
coords = coords.reshape(8,4,5,3) #(8,4,5,3)

#calculate broadcasted difference
diff = (coords[:,:,None,:,None,:] - coords[:,None,:,None,:,:]) #(8, 4, 4, 5, 5, 3)

#Calculate the distances
distances = np.linalg.norm(diff, axis=-1) #(8, 4, 4, 5, 5)
distances = distances.reshape(8,4,4,5*5)  #(8, 4, 4, 25) reshape for calling argmin

#Calculate the min distance
min_distances = distances.min(axis=-1) #(8, 4, 4)
min_index = distances.argmin(axis=-1)

In [267]:
min_index[...,None,None].choose(diff.transpose(0,1,2,5,3,4).reshape(8,4,4,3,5*5))

ValueError: invalid entry in choice array

In [275]:
a = np.array([[0.5, 0.5],
              [0.6, 0.4]])

b = np.array([[[1, 2, 1],
            [1, 3, 1]],

           [[2, 1, 2],
            [3, 1, 3]]])

c = np.array([[1. , 2.5, 1. ],
              [2.4 , 1.2, 2.4 ]])

np.einsum('ij,ijk->ik',a,b)

array([[1. , 2.5, 1. ],
       [2.4, 1. , 2.4]])

In [277]:
np.einsum('ij,ijk->ik',a,b)

array([[1. , 2.5, 1. ],
       [2.4, 1. , 2.4]])

In [330]:
np.tensordot(a,b, axes=[1,1]).diagonal().T

array([[1. , 2.5, 1. ],
       [2.4, 1. , 2.4]])

In [338]:
(a[:,:,None]*b).sum(1)

array([[1. , 2.5, 1. ],
       [2.4, 1. , 2.4]])

In [341]:
a = np.array([[1, 2, 3, 4, 5, 6],
              [1, 2, 3, 4, 5, 6]])

In [342]:
a

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [390]:
import pandas as pd

foo = pd.DataFrame({
                    'wag' : [1, 1, 1, 1, 44, 44, 44, 56, 56, 56, 56],
                     'A' :  [10, 8, 7, 3, 13, 22, 18, 43, 40, 38, 12],
                     'B' : [55, 48, 37, 34, 15, 12, 5, 1, 2, 2, 1]
                     })

In [391]:
foo

wag   A   B
0     1  10  55
1     1   8  48
2     1   7  37
3     1   3  34
4    44  13  15
5    44  22  12
6    44  18   5
7    56  43   1
8    56  40   2
9    56  38   2
10   56  12   1

In [386]:
foo.groupby('wag').last().index

Int64Index([1, 44, 56], dtype='int64', name='wag')

In [423]:
list(foo.groupby('wag'))[0][1][['A','B']].apply(lambda x: x)

A   B
0  10  55
1   8  48
2   7  37
3   3  34

In [ ]:
foo.min(axis=1).groupby(foo['wag'], sort=False).agg(list).tolist()

In [252]:
import numpy as np
val_arr = np.arange(27).reshape(3,3,3)
z_indices = np.array([[1,0,2],
                      [0,0,1],
                      [2,0,1]])

In [253]:
z_indices.shape

(3, 3)

In [256]:
z_indices.choose(val_arr)

array([[ 9,  1, 20],
       [ 3,  4, 14],
       [24,  7, 17]])

In [ ]:
8,4,4,3

In [ ]:
8,4,4,1 <- (0,24)

In [ ]:
8,4,4,1,3

array([[[ True,  True,  True,  True],
        [False,  True,  True,  True],
        [False, False,  True,  True],
        [False, False, False,  True]],

       [[ True,  True,  True,  True],
        [False,  True,  True,  True],
        [False, False,  True,  True],
        [False, False, False,  True]],

       [[ True,  True,  True,  True],
        [False,  True,  True,  True],
        [False, False,  True,  True],
        [False, False, False,  True]],

       [[ True,  True,  True,  True],
        [False,  True,  True,  True],
        [False, False,  True,  True],
        [False, False, False,  True]],

       [[ True,  True,  True,  True],
        [False,  True,  True,  True],
        [False, False,  True,  True],
        [False, False, False,  True]],

       [[ True,  True,  True,  True],
        [False,  True,  True,  True],
        [False, False,  True,  True],
        [False, False, False,  True]],

       [[ True,  True,  True,  True],
        [False,  True,  True,  True],


masked_array(
  data=[[[--, --, --, --],
         [0.136075965019958, --, --, --],
         [0.28791733568765504, 0.18143277717651862, --, --],
         [0.49111909087740274, 0.2893218913892311, 0.05540328738426811,
          --]],

        [[--, --, --, --],
         [0.13109109176335634, --, --, --],
         [0.28240261843378367, 0.3111310134401459, --, --],
         [0.09477266737267864, 0.1368614290505418, 0.0903556352647111,
          --]],

        [[--, --, --, --],
         [0.22457062179919635, --, --, --],
         [0.10372725607999458, 0.1222528223930379, --, --],
         [0.07562920689234078, 0.2127787811299136, 0.3186541011713909,
          --]],

        [[--, --, --, --],
         [0.2991308729635199, --, --, --],
         [0.23608284172770955, 0.3532582646905768, --, --],
         [0.1264696293366745, 0.14136520285588908, 0.278020547354321,
          --]],

        [[--, --, --, --],
         [0.32825792474510573, --, --, --],
         [0.1881136523917278, 0.214935386

In [176]:
np.tril(min_distances).min()

0.0

In [ ]:
np.min(a[np.nonzero(a)])

In [173]:
min_distances[0]

array([[0.        , 0.22865803, 0.12158097, 0.36184721],
       [0.22865803, 0.        , 0.18405683, 0.26578856],
       [0.12158097, 0.18405683, 0.        , 0.27822988],
       [0.36184721, 0.26578856, 0.27822988, 0.        ]])

In [166]:
distances.shape

(8, 4, 4, 5, 5)

In [480]:
array1 = np.array([np.nan,np.nan,np.nan,np.nan,2,np.nan,1,np.nan,np.nan,5,np.nan,np.nan,6,np.nan,10,9,np.nan])
array2 = np.array([np.nan,np.nan,np.nan,np.nan,45,np.nan,33,np.nan,np.nan,32,np.nan,np.nan,44,np.nan,10,53,np.nan])

In [448]:
idx = np.ma.masked_array(array1, np.isnan(array1))
vals = np.ma.masked_array(array2, np.isnan(array2))

In [455]:
idx = np.ma.masked_array(array1.argsort(), np.isnan(array1))

In [458]:
idx

masked_array(data=[--, --, --, --, 15, --, 0, --, --, 10, --, --, 3, --,
                   1, 7, --],
             mask=[ True,  True,  True,  True, False,  True, False,  True,
                    True, False,  True,  True, False,  True, False, False,
                    True],
       fill_value=999999)

In [470]:
idx = array1[~np.isnan(array1)].argsort()

array2[~np.isnan(array2)] = array2[~np.isnan(array2)][idx]

array2

array([nan, nan, nan, nan, 33., nan, 45., nan, nan, 32., nan, nan, 44.,
       nan, 53., 10., nan])

In [474]:
idx = array1[~np.isnan(array1)].argsort()

array2[~np.isnan(array2)] = array2[~np.isnan(array2)][idx]

array2

array([nan, nan, nan, nan, 33., nan, 45., nan, nan, 32., nan, nan, 44.,
       nan, 53., 10., nan])

In [482]:
np.where(~np.isnan(array2), array2)

AttributeError: 'numpy.ndarray' object has no attribute 'isna'

In [488]:
ordered = array2[array1.argsort()]
ordered = ordered[~np.isnan(ordered)]

array2[~np.isnan(array2)] = ordered


array2

array([nan, nan, nan, nan, 33., nan, 45., nan, nan, 32., nan, nan, 44.,
       nan, 53., 10., nan])

In [456]:
vals[idx]

masked_array(data=[33.0, 45.0, 32.0, 44.0, 53.0, 10.0, --, --, --, --, --,
                   --, --, --, --, --, --],
             mask=[False, False, False, False, False, False,  True,  True,
                    True,  True,  True,  True,  True,  True,  True,  True,
                    True],
       fill_value=1e+20)

In [450]:
vals

masked_array(data=[--, --, --, --, 45.0, --, 33.0, --, --, 32.0, --, --,
                   44.0, --, 10.0, 53.0, --],
             mask=[ True,  True,  True,  True, False,  True, False,  True,
                    True, False,  True,  True, False,  True, False, False,
                    True],
       fill_value=1e+20)

In [442]:
array2[idx]

array([33., 45., 32., 44., 53., 10., nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan])

In [ ]:
sorted()

In [ ]:
Q V R

1,2,3,4,5 vs 1,2,3,4,5

In [490]:
df1 = pd.read_clipboard()

In [542]:
df1

name Code
0  1234567  H74

In [ ]:
name	Code
1234567	J11
1234321	J12

In [560]:
df2 = pd.read_clipboard()

In [561]:
df2

name Code
0  1234567  J11
1  1234321  J12

In [556]:
df2.set_index('name').join(df1.set_index('name'), lsuffix='_')\
                     .ffill(1)['Code']\
                     .reset_index()

name Code
0  1234567.0  H74
1  1234321.0  J12

In [597]:
df = pd.DataFrame(list('aaabccccddeff'), columns=['A'])

idx = df.groupby(['A'])['A'].transform('count').lt(2)
df.loc[idx, 'A'] = 'others'
df

A
0        a
1        a
2        a
3   others
4        c
5        c
6        c
7        c
8        d
9        d
10  others
11       f
12       f

In [603]:
mylist = [['I','have','an','apple'],['she','have','an','orange']]

df = pd.DataFrame({'text':mylist})
print(df)

                      text
0     [I, have, an, apple]
1  [she, have, an, orange]

                      text
0     [I, have, an, apple]
1  [she, have, an, orange]


In [ ]:
['A','A','A','B','B','C','D','D','E'

0.09179275874969095

merchant_id  month  total_transactions  total_fraud
0       113025      0                 126           24
1       113025      1                 299           58
2       113025      4                   4            0
3       113025      6                  17            3
4       113025     11                 160           31

In [742]:
import numpy as np
import pandas as pd
import itertools
import random

#Creating Dummy dataset
merchantid = np.random.randint(111111,999999,(500,))
merchant_months = list(itertools.product(merchantid, range(12)))
merchant_months_missing = sorted(random.sample(merchant_months, int(len(merchant_months)*0.4)))

df = pd.DataFrame(merchant_months_missing, columns=['merchant_id','month'])
df['total_transactions'] = np.random.randint(1,300,(2400,))
df['total_fraud'] = (df['total_transactions']*np.random.random()).astype(int)
df.head()


############################################

print('original data shape ->', df.shape)

############################################
#Remove small merchants with less than 100 max transactions / month

condition = df.groupby(['merchant_id'])['total_transactions'].max()<100
small_merchants = condition[condition].index

df = df[~df['merchant_id'].isin(small_merchants)]
print('after small merchants ->', df.shape)

############################################
#Remove edge merchants who may have transctions in prev/next year

edge_merchants = df[(df['month'].isin([0,11]))&(df['total_transactions']<10)]['merchant_id'].unique()

df = df[~df['merchant_id'].isin(edge_merchants)]
print('after edge merchants ->', df.shape)

############################################
#Keep merchants with less than equal to 3 months of transactions

condition = df.groupby(['merchant_id'])['month'].count().le(3)
three_month_merchants = condition[condition].index

df = df[df['merchant_id'].isin(three_month_merchants)]
print('after 3 month merchants ->', df.shape)

############################################
#Keep merchants who have 3 consecutive months of transactions

condition = df.groupby(['merchant_id'])['month'].apply(list).apply(lambda x: x == list(range(min(x), max(x)+1)))
consecutive_months_merchants = condition[condition].index

df = df[df['merchant_id'].isin(consecutive_months_merchants)]
print('after consecutive month merchants ->', df.shape)

############################################
#Compute metrix fraud rate / BPS

final = df.groupby('merchant_id')['total_fraud'].sum()/df.groupby('merchant_id')['total_transactions'].sum()
final = (final*100).reset_index()
final.columns = ['merchant_id', 'BPS']
print('final metric dataframe ->', final.shape)
final

original data shape -> (2400, 4)
after small merchants -> (2369, 4)
after edge merchants -> (2296, 4)
after 3 month merchants -> (246, 4)
after consecutive month merchants -> (18, 4)
final metric dataframe -> (11, 2)


merchant_id        BPS
0        299781  38.053097
1        347099  38.078292
2        378452  37.943262
3        417558  38.207547
4        495317  38.141026
5        531805  38.073394
6        539172  38.058252
7        647945  37.884615
8        679103  37.918216
9        823698  38.011696
10       861204  37.771739

In [762]:
[800/i for i in range(1,4)]

[800.0, 400.0, 266.6666666666667]

In [765]:
from tensorflow.keras.layers import Conv2D, MaxPooling2D, UpSampling2D, Input, Flatten, Reshape/
from tensorflow.keras import Model

SyntaxError: invalid syntax (<ipython-input-765-6b20ecc8d875>, line 1)

In [774]:
x = Input(shape=(800, 20,1)) 

# Encoder
conv1_1 = Conv2D(4, (3, 3), activation='relu', padding='same')(x)
pool1 = MaxPooling2D((2, 2), padding='same')(conv1_1)
conv1_2 = Conv2D(8, (3, 3), activation='relu', padding='same')(pool1)
pool2 = MaxPooling2D((2, 2), padding='same')(conv1_2)
conv1_3 = Conv2D(16, (3, 3), activation='relu', padding='same')(pool2)
h = MaxPooling2D((2, 1), padding='same')(conv1_3)

# f = Flatten()(h)
# f = Reshape()
# # Decoder

conv2_1 = Conv2D(16, (3, 3), activation='relu', padding='same')(h)
up1 = UpSampling2D((2, 2))(conv2_1)
conv2_2 = Conv2D(8, (3, 3), activation='relu', padding='same')(up1)
up2 = UpSampling2D((2, 2))(conv2_2)
conv2_3 = Conv2D(4, (3, 3), activation='sigmoid', padding='same')(up2) #<--- ADD IT HERE
up3 = UpSampling2D((2, 1))(conv2_3)
r = Conv2D(1, (3, 3), activation='sigmoid', padding='same')(up3)

model = Model(inputs=x, outputs=r)
model.compile(optimizer='adadelta', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "model_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_16 (InputLayer)        [(None, 800, 20, 1)]      0         
_________________________________________________________________
conv2d_101 (Conv2D)          (None, 800, 20, 4)        40        
_________________________________________________________________
max_pooling2d_45 (MaxPooling (None, 400, 10, 4)        0         
_________________________________________________________________
conv2d_102 (Conv2D)          (None, 400, 10, 8)        296       
_________________________________________________________________
max_pooling2d_46 (MaxPooling (None, 200, 5, 8)         0         
_________________________________________________________________
conv2d_103 (Conv2D)          (None, 200, 5, 16)        1168      
_________________________________________________________________
max_pooling2d_47 (MaxPooling (None, 100, 5, 16)        0  

In [799]:
x_train = np.random.random((16,800,20,1))

model.fit(x_train, x_train, epochs=2)

Epoch 1/2
1/1 [==============================] - 0s 180ms/step - loss: 0.7526 - accuracy: 0.0000e+00
Epoch 2/2
1/1 [==============================] - 0s 189ms/step - loss: 0.7526 - accuracy: 0.0000e+00
<tensorflow.python.keras.callbacks.History at 0x7fa85a9896d0>

Epoch 1/2
1/1 [==============================] - 0s 180ms/step - loss: 0.7526 - accuracy: 0.0000e+00
Epoch 2/2
1/1 [==============================] - 0s 189ms/step - loss: 0.7526 - accuracy: 0.0000e+00


In [813]:
l = [[1,2,3], [1,2,3]]

In [814]:
[[str(i) for i in j] for j in l]

[['1', '2', '3'], ['1', '2', '3']]

In [815]:
list(map(lambda x: list(map(str, x)), l))

[['1', '2', '3'], ['1', '2', '3']]

In [816]:
output = []

for i in l:
    sublist = []
    for j in i:
        sublist.append(str(j))
    output.append(sublist)
    
output

[['1', '2', '3'], ['1', '2', '3']]

In [817]:
for i in range(len(l)):
    for j in range(len(l[i])):
        l[i][j] = str(l[i][j])
l

[['1', '2', '3'], ['1', '2', '3']]