In [1]:
import pandas as pd
import numpy as np

In [ ]:
df1 = pd.read_clipboard('|')

In [ ]:
df2 = pd.read_clipboard('|')

In [ ]:
df1

In [ ]:
df2

In [ ]:
df2.to_dict('list')

In [ ]:
df1.merge(df2).drop_duplicates().shape == df1.drop_duplicates().shape

In [ ]:
df1 = pd.DataFrame({'A ': [1], ' B ': [2], ' C': [3]})
df2 = pd.DataFrame({'A ': [2, 3, 1, 5], ' B ': [5, 2, 2, 1], ' C': [5, 7, 3, 5]})

(df1.merge(df2) == df1).all().all()

In [ ]:
d = {'a': [0,1,0,1,1,1], 'b': [1,1,1,1,1,1], 'c': [0,0,0,0,0,1], 'd': [1,0,1,1,1,0]}
dct = {'a':'top','b':'bot','c':'top','d':'bot'}
df = pd.DataFrame(d)
df

In [ ]:
df.join(df.groupby(df.columns.map(dct), 1).sum())

In [ ]:
n = 3
arr = np.array([10**i for i in range(n)]) #array([  1,  10, 100])
p[:genome.size]*genome*arr[:,None] + p[:genome.size]*~genome

In [ ]:
p[:genome.size]*genome*arr[:,None]

In [ ]:
p[:genome.size]*~genome

In [ ]:
n = (p.size//genome.size)+1
np.repeat(genome)

In [ ]:
genome

In [ ]:
np.where(np.repeat(genome,3), p, 0)

In [ ]:
np.where(np.repeat(genome,3), p, 0)

In [ ]:
np.tile(genome,3)[original]=p

In [ ]:
p[:genome.size][genome]

In [ ]:
idx = np.pad(genome, (0,p.size-genome.size), constant_values=True)
output = np.tile(genome,3).astype(float)
positions = np.argwhere(np.tile(genome,3))
output[positions] = p[idx,None]
output.reshape(-1,genome.size)

In [ ]:
positions = np.repeat(genome[None,:], 3, 0)
np.where(positions, a, 0)

In [ ]:
out

In [ ]:
np.tile(genome,3)

In [ ]:
# original array -- for references only
arr = np.arange(12).reshape(-1,6)

# keep indexes
keep = np.array([False,  True,  True,  False,  True,  True])

# array after removing the columns
removed_arr = arr[:,keep]

# output array
out = np.zeros((removed_arr.shape[0], len(keep)), dtype=removed_arr.dtype)

# copy the values of `removed_arr` to output
out[:, keep] = removed_arr

In [ ]:
keep

In [ ]:
from treelib import Node, Tree

In [ ]:
from sklearn.datasets import load_iris
from sklearn import tree
import matplotlib.pyplot as plt

#load data
iris = load_iris()

#model training
clf = tree.DecisionTreeClassifier(random_state=0)
clf.fit(iris.data, iris.target)

#plotting
fig = plt.figure(figsize=(10,10))
tree.plot_tree(clf, filled=True, impurity=False, proportion=True)
plt.show()

In [ ]:
df = pd.DataFrame({'First Name':['Freddie', 'John', 'David', '', 'Joseph', ''], 
                   'Last Name':['Mercury', 'Lennon', 'Bowie','', '', 'Jovi']})

df['fullname'] = df['First Name']+' '+df['Last Name']
df['fullname'] = ['Freddie Mercury', 'John Lennon', 'David Bowie','John Doe', 'Joseph', 'Jovi']
df

In [ ]:
print(df.to_dict('list'))

In [ ]:
d = {'First Name': ['Freddie', 'John', 'David', '', 'Joseph', ''], 
     'Last Name': ['Mercury', 'Lennon', 'Bowie', '', '', 'Jovi'], 
     'fullname': ['Freddie Mercury', 'John Lennon', 'David Bowie', 'John Doe', 'Joseph', 'Jovi']}

df = pd.DataFrame(d)

In [ ]:
import ast

In [ ]:
strng = "0.000000000000000E+000, 2*2.400000000000000E-002  , 97*0.000000000000000E+000  ,"

In [ ]:
out = [eval(i.strip().replace('*','*[')+']' if '*' in i else '['+i.strip()+']') for i in strng.split(',') if len(i)>0]
                  
                  
print(out)               

In [ ]:
a = strng.split(',')
lst=[]
for item in a:
    print("intem=", item)
    i= item.split("*")
    if len(i) >1:
        print(int(i[0])*i[1])
        lst.append(int(i[0])*i[1])
    else:
        lst.append(i[0])
print("================")
print(lst)

In [ ]:
df_data_4 = np.random.random((65000,3))

v_data = df_data_4[:(1083*60),:].reshape((1083,60,-1))
v_data.shape

(1083, 60, 3)

In [ ]:
import numpy as np

df_data_4 = np.random.random((65000,3)) #<-- just replace this with your actual df_data_4

v_data = df_data_4[:(1083*60),:].reshape((1083,60,-1))
v_data.shape

In [ ]:
# d looks like - 
# defaultdict(list,
#             {'a': [0],
#              'b': [0, 1, 2],
#              'c': [1],
#              'd': [2],
#              'e': [2, 3],
#              'g': [2],
#              'f': [3]})

In [ ]:
from collections import defaultdict


lol = [[0,'a'], [0,'b'],
       [1,'b'], [1,'c'],
       [2,'d'], [2,'e'],
       [2,'g'], [2,'b'],
       [3,'e'], [3,'f']]


d = defaultdict(list)

for v,k in lol:
    d[k].append(v)
    
[[v,k] for k,vs in d.items() for v in vs if len(vs)>1]

[[0, 'b'], [1, 'b'], [2, 'b'], [2, 'e'], [3, 'e']]

In [ ]:
import pandas as pd
df = pd.DataFrame(lol, columns=['val','key'])
dups = df[df['key'].duplicated(keep=False)]
result = list(dups.to_records(index=False))
print(result)

[(0, 'b'), (1, 'b'), (2, 'e'), (2, 'b'), (3, 'e')]

In [ ]:
import numpy as np

lol = [[0,'a'], [0,'b'],
       [1,'b'], [1,'c'],
       [2,'d'], [2,'e'],
       [2,'g'], [2,'b'],
       [3,'e'], [3,'f']]

arr = np.array(lol)
arr

In [ ]:
list(zip(uq[0][1:], splits))

In [ ]:
uq = np.unique(arr[:, 1], return_index=True)
splits = np.split(arr[:,0], uq[1][1:])

[i for i in zip(uq[0])]

In [ ]:
np.split(arr[:,0], np.unique(arr[:, 1], return_index=True)[1][1:])

In [ ]:
import numpy as np

u, c = np.unique(arr[:,1], return_counts=True)
dup = u[c > 1]

result = arr[(arr[:,1]==dup[:,None]).any(0)]
result

array([['0', 'b'],
       ['1', 'b'],
       ['2', 'e'],
       ['2', 'b'],
       ['3', 'e']], dtype='<U21')

In [ ]:
dup

In [ ]:
lol

In [ ]:
stack

In [ ]:
stack = []
stack.append(lol[0])

for i in lol:
    if stack[-1][1]!=i[1]:
        stack.append(i)

In [ ]:
stack

In [ ]:
myDict = {"word" : [10],
          "other word" : [16]}

In [ ]:
output = {k:v[0] for k,v in myDict.items()}
print(output)

In [ ]:
for k,v in output.items():
    print(k,v)
    
word 10
other word 16

In [ ]:
for k,v in myDict.items():
    print(k,v[0])
    
word 10
other word 16

In [ ]:
df = pd.DataFrame({'39' : [1, np.nan, 3],
                   '40' : [2, 4, 5],
                   '41' : [3, 1, 4],
                   '42' : [2, 5, 2],
                   '43' : [1, 1, np.nan],
                   'start' : [39, 40, 41],
                   'end' : [41, 41, 43]})

In [ ]:
df = df.set_index(["start", "end"]).stack()
idx = df.index
values = idx.get_level_values(2).astype(int)
start = idx.get_level_values(0)
end = idx.get_level_values(1)

df.where((values >= start) & (values <= end)).unstack().reset_index()

In [ ]:
df = df.set_index(["start", "end"]).stack()
df

In [ ]:
idx = df.index
idx

In [ ]:
values = idx.get_level_values(2).astype(int)
values

In [ ]:
start = idx.get_level_values(0)
start

In [ ]:
end = idx.get_level_values(1)


In [ ]:
df.where((values>=start) & (values <= end)).unstack().reset_index()

In [ ]:
df2 = pd.DataFrame({'51' : [1, np.nan, 3],
                   '52' : [2, 4, 5],
                   '1' : [3, 1, 4],
                   '2' : [2, 5, 2],
                   '3' : [1, 1, 3],
                   'start' : [51, 52, 52],
                   'end' : [1, 2, 1]})

In [ ]:
hsh_inv

In [ ]:
hsh = dict(enumerate(df2.columns))
hsh_inv = {int(v):k for k,v in hsh.items()}
df2 = df2.replace(hsh_inv)
print(df2)
df2.columns = df2.columns.to_series().map(hsh_inv)
df2

In [ ]:
df2 = df2.set_index([hsh_inv["start"], hsh_inv["end"]]).stack()
idx = df2.index
values = idx.get_level_values(2).astype(int)
start = idx.get_level_values(0)
end = idx.get_level_values(1)

df2.where((values >= start) & (values <= end)).unstack().reset_index()

In [ ]:
n = int(input("Enter a number:"))
S = 0

for j in range(1,n+1):
    if j % 2 == 0:
        S -= 1/j
    else:
        S += 1/j
    # print(j)
    # print(S)

print(S)

In [ ]:
S = 1 - 1/2 + 1/3 - 1/4 ... 1/n

In [ ]:
n = int(input('Enter a number: '))
S = sum((1/(i+1))*(-1)**i for i in range(n))
S

In [ ]:
import matplotlib.pyplot as plt

#In function form
def f(n): return sum((1/(i+1))*(-1)**i for i in range(n))

#Plotting
y = [f(i+1) for i in range(100)]
plt.plot(y)

In [ ]:
num1, op, num2 = input('enter equation: ').split(' ')
num1, num2 = float(num1), float(num2)

if op == "+":
    print(num1 + num2)
elif op == "-":
    print(num1 - num2)
elif op == "*":
    print(num1 * num2)
elif op == "/":
    print(num1 / num2)

else:
    print(" Enter a valid operator...")
    
enter equation: 3 * 3
9.0

In [ ]:
from ast import literal_eval

eq = input('enter equation: ')
result = literal_eval(eq)

In [ ]:
from collections import defaultdict, Counter

String = "Today was a very a good day. Tomorrow might be a better day"
tokens = String.replace('.','').split()


d = defaultdict(list)

for k,v in Counter(tokens).items():
    if k not in d[v]:
        d[v].append(k)
    
output = dict(d)
print(output)

In [ ]:
uq = np.unique(tokens, return_counts=True)
list(zip(uq[0], uq[1]))

[('Today', 1),
 ('Tomorrow', 1),
 ('a', 3),
 ('be', 1),
 ('better', 1),
 ('day', 2),
 ('good', 1),
 ('might', 1),
 ('very', 1),
 ('was', 1)]

In [ ]:
df['auc_all']

In [2]:
df = pd.DataFrame({'auc_all':['(0.5, 0.6)', '(0.5, 0.6)', '(0.5, 0.6)']})
df

auc_all
0  (0.5, 0.6)
1  (0.5, 0.6)
2  (0.5, 0.6)

In [3]:
type(df['auc_all'][0])

str

In [4]:
def convert_str_into_tuple(self, string):
    splitted_tuple = string.split(',')
    value1 = float(splitted_tuple[0][1:])
    value2 = float(splitted_tuple[1][1:-1])
    return (value1, value2)

df['auc_all'].apply(convert_str_into_tuple)

TypeError: convert_str_into_tuple() missing 1 required positional argument: 'string'

In [51]:
data = np.array([
     [1,2,3],
     [1,2,3],
     [1,2,101],
     [4,5,111],   
     [4,5,6], 
     [4,5,6], 
     [4,5,101], 
     [4,5,112], 
     [4,5,6], 
     ])

In [52]:
idx = np.vstack([np.roll(data==101,-1,0)[:-1], np.array([False, False, False])])
data[idx] = 10001


array([[    1,     2,     3],
       [    1,     2, 10001],
       [    1,     2,   101],
       [    4,     5,   111],
       [    4,     5,     6],
       [    4,     5, 10001],
       [    4,     5,   101],
       [    4,     5,   112],
       [    4,     5,     6]])

In [53]:
data

array([[    1,     2,     3],
       [    1,     2, 10001],
       [    1,     2,   101],
       [    4,     5,   111],
       [    4,     5,     6],
       [    4,     5, 10001],
       [    4,     5,   101],
       [    4,     5,   112],
       [    4,     5,     6]])

In [70]:
l = [('a',1,'b',2,'c',3), ('d',1,'e',2),('f',1,'g',2,'h',3,'i',4)]

[tuple([item for item in sublist if not isinstance(item, int)]+[sublist[-1]]) for sublist in l]

#|___________________________________________________________| |____________| 
#                            |                                       |
#  Same as your method, iterating on n-1 items for each tuple        |
#                                                               append last item
#|____________________________________________________________________________________________|
#                                           |
#   Iterate over the list and then iterate over each sublist (tuples) with condition


[('a', 'b', 'c', 3), ('d', 'e', 2), ('f', 'g', 'h', 'i', 4)]

[('a', 'b', 'c', 3), ('d', 'e', 2), ('f', 'g', 'h', 'i', 4)]

In [69]:
[[j for j in i][:-1]+[i[-1]] for i in l]

[['a', 1, 'b', 2, 'c', 3], ['d', 1, 'e', 2], ['f', 1, 'g', 2, 'h', 3, 'i', 4]]

In [71]:
[(i,j) for i,j in l]

ValueError: too many values to unpack (expected 2)

[('a', 'b', 'c'), ('d', 'e'), ('f', 'g', 'h', 'i')]

In [73]:
df1 = pd.DataFrame(
    {
        "column0": [["xx, aa", "xx, aa"]],
        "column1": [["yy, bb","yy, aa"]],
        "column2": [["cc, xx", "cc, xx"]]})

In [79]:
flatten = lambda x: [i for j in x for i in j.split(',')]

df1.applymap(flatten).apply(pd.Series.explode).unstack().reset_index()

level_0  level_1    0
0   column0        0   xx
1   column0        0   aa
2   column0        0   xx
3   column0        0   aa
4   column1        0   yy
5   column1        0   bb
6   column1        0   yy
7   column1        0   aa
8   column2        0   cc
9   column2        0   xx
10  column2        0   cc
11  column2        0   xx

In [7]:
df1

column0           column1           column2
0  [xx, aa, xx, aa]  [yy, bb, yy, aa]  [cc, xx, cc, xx]

In [57]:
df1['column1']

0    [yy, bb, yy, aa]
Name: column1, dtype: object

In [63]:
d

TypeError: descriptor 'split' for 'str' objects doesn't apply to a 'Series' object

In [33]:
df1.apply(lambda x: x.to_list(),1)

0    [[xx, aa, xx, aa], [yy, bb, yy, aa], [cc, xx, ...
dtype: object

In [60]:
df1['column0'].explode()

0    [xx,, aa]
0    [xx,, aa]
Name: column0, dtype: object

In [81]:
import numpy as np
from scipy import stats

In [86]:
Nbank = np.array([[2, 3, 1],
                  [1, 2, 2],
                  [3, 2, 1],
                  [3, 2, 1],
                  [2, 3, 2],
                  [2, 2, 3],
                  [1, 1, 3],
                  [2, 1, 1],
                  [2, 2, 3],
                  [1, 1, 1],
                  [2, 1, 1],
                  [2, 3, 1],
                  [1, 2, 1]])

modes, bins = stats.mode(Nbank,1)

In [88]:
modes.T

array([[1, 2, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1]])

In [89]:
bins.T

array([[1, 2, 1, 1, 2, 2, 2, 2, 2, 3, 2, 1, 2]])

In [95]:
np.unique(Nbank,axis=1, return_counts=True)

(array([[1, 2, 3],
        [2, 1, 2],
        [1, 3, 2],
        [1, 3, 2],
        [2, 2, 3],
        [3, 2, 2],
        [3, 1, 1],
        [1, 2, 1],
        [3, 2, 2],
        [1, 1, 1],
        [1, 2, 1],
        [1, 2, 3],
        [1, 1, 2]]),
 array([1, 1, 1]))

In [53]:
df1.apply(pd.Series.explode)

column0 column1 column2
0  xx, aa  yy, bb  cc, xx
0  xx, aa  yy, aa  cc, xx

In [97]:
l = [1,2,3,4,5]

In [99]:
[~i for i in l]

[-2, -3, -4, -5, -6]

In [103]:
[l[~i] for i in range(len(l))]

[5, 4, 3, 2, 1]

In [105]:
import numpy as np

arr = np.random.random((10,10))

arr.strides

(80,8)

(80, 8)

In [110]:
# Importing required libraries
import numpy as np
import pandas as pd

# Importing dataset
dataset = pd.DataFrame(np.random.random((100,3)))
X = dataset.iloc[:, 1: -1].values
y = dataset.iloc[:, -1].values

y = y.reshape(len(y), 1)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
scy = StandardScaler()
scX = StandardScaler()
X = scX.fit_transform(X)
y = scy.fit_transform(y)

# Training SVR model
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X, y)

# Predicting results from SCR model
scy.inverse_transform(regressor.predict(scX.transform([[6.5]])))

/Users/akshay/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([0.53321341])