In [1]:
import pandas as pd
import numpy as np
import itertools
import collections

In [2]:
a = [1,2,3,4,2,2,3,1,4,4,4]

In [4]:
max(a,key=a.count)

4

TypeError: list.count() takes exactly one argument (0 given)

In [30]:
import numpy as np
from sklearn.metrics import make_scorer
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

#define custom function which returns single output as metric score
def NMAPE(y_true, y_pred): 
    return 1 - np.mean(np.abs((y_true - y_pred) / y_true)) * 100

#make scorer from custome function
nmape_scorer = make_scorer(NMAPE)

#dummy data
X = np.random.random((1000,10))
y = np.random.random(1000,)

#cross validation score on model
reg = LinearRegression()
cross_val_score(reg, X, y, scoring=nmape_scorer, cv=5)

array([-4453.67565485,  -148.201211  ,  -222.92820259,  -185.27855064,
        -657.27927049])

array([-4453.67565485,  -148.201211  ,  -222.92820259,  -185.27855064,
        -657.27927049])

array([-0.26640576, -0.23729053, -0.24491062, -0.26058433, -0.24939438])